<a href="https://colab.research.google.com/github/FariaTabassum/Machine-learing-master-class/blob/main/life_insurance_using_logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Importing libraries**


In [1]:
import pandas as pd #useful for loading dataset
import numpy as np #to perform array

### **Choose Dataset file from Local Directory**

In [2]:
from google.colab import files
uploaded = files.upload()

Saving insurance_data.csv to insurance_data.csv


### **load Dataset**

In [3]:
df = pd.read_csv('insurance_data.csv')
print(df) 

    age  bought_insurance
0    22                 0
1    25                 0
2    47                 1
3    52                 0
4    46                 1
5    56                 1
6    55                 0
7    60                 1
8    62                 1
9    61                 1
10   18                 0
11   28                 0
12   27                 0
13   29                 0
14   49                 1
15   55                 1
16   25                 1
17   58                 1
18   19                 0
19   18                 0
20   21                 0
21   26                 0
22   40                 1
23   45                 1
24   50                 1
25   54                 1
26   23                 0


### **Summarize dataset**

In [4]:
print(df.shape)
print(df.head(5))

(27, 2)
   age  bought_insurance
0   22                 0
1   25                 0
2   47                 1
3   52                 0
4   46                 1


### **Segregate Dataset into X(Input/IndependentVariable) & Y(output/dependentVariable)**





In [5]:
X = df.iloc[:, :-1].values
X

array([[22],
       [25],
       [47],
       [52],
       [46],
       [56],
       [55],
       [60],
       [62],
       [61],
       [18],
       [28],
       [27],
       [29],
       [49],
       [55],
       [25],
       [58],
       [19],
       [18],
       [21],
       [26],
       [40],
       [45],
       [50],
       [54],
       [23]])

In [6]:
Y = df.iloc[:, -1].values
Y

array([0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0])

###  **Spliting Dataset into Train & Test**

In [12]:
 from sklearn.model_selection import train_test_split
 X_train, X_test,Y_train, Y_test = train_test_split(X, Y ,test_size= 0.25 ,random_state= 0)

### **Feature Scaling**

we scale our data to make all featuewa contribute equally to the result
* Fit_Transform- fit method is calculating the mean  and variance of each of the features present in our data
*  Transform- Transform method is transforming all the features using the respective mean and variance

we want our data to be a completely new and a surprise set for our model







In [8]:
#from sklearn.preprocessing import StandardScaler
#sc= StandardScaler()
#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)
#print(X_train)

[[-0.48631272]
 [-1.163457  ]
 [-0.97878129]
 [-0.732547  ]
 [-0.732547  ]
 [-1.163457  ]
 [-0.85566414]
 [ 1.05265157]
 [ 1.54512015]
 [ 1.11421014]
 [ 0.560183  ]
 [-1.10189843]
 [ 1.48356157]
 [ 1.422003  ]
 [ 0.19083157]
 [ 0.92953443]
 [-0.91722272]
 [-0.67098843]
 [ 1.11421014]
 [-0.60942986]]


### **Training**

In [13]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state = 0)
model.fit(X_train,Y_train)

LogisticRegression(random_state=0)

### **Predicting**

In [14]:
age = int(input ("Enter New People's Age : "))
new= [[age]]
result = model.predict(new)
print(result)
if result == 1:
   print("Will take insurance")
else:
  print("Will not take insurance")

Enter New People's Age : 34
[0]
Will not take insurance


### **Predict for all Test Data**

In [15]:
Y_pred=model.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]]


### **Accuracy**

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(Y_test,Y_pred)

print ("Confusion Matrix : ")
print(cm)

print("Accuracy of the model : {0}% " . format(accuracy_score(Y_test,Y_pred)*100))

Confusion Matrix : 
[[1 0]
 [0 6]]
Accuracy of the model : 100.0% 
